"""add url_prefix to Automation

Revision ID: 0384c22a9751
Revises: 43e48ad1eb52
Create Date: 2025-08-22 08:52:16.616627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0384c22a9751'
down_revision = '43e48ad1eb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_prefix', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('automations', schema=None) as batch_op:
        batch_op.drop_column('url_prefix')

    # ### end Alembic commands ###
