"""no_of_iterations in Blog Post

Revision ID: 43e48ad1eb52
Revises: 2a0a50cd79c3
Create Date: 2025-08-21 14:50:15.183166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e48ad1eb52'
down_revision = '2a0a50cd79c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_blog_posts', schema=None) as batch_op:

        batch_op.add_column(sa.Column('no_of_iterations', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_blog_posts', schema=None) as batch_op:
        batch_op.drop_column('no_of_iterations')

    # ### end Alembic commands ###
