"""add post_context as String into the BlogPostIteration model.

Revision ID: 528adf17f103
Revises: 0384c22a9751
Create Date: 2025-08-23 15:29:25.613800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528adf17f103'
down_revision = '0384c22a9751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_iterations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_context', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_iterations', schema=None) as batch_op:
        batch_op.drop_column('post_context')

    # ### end Alembic commands ###
