"""Add: BlogPostContext model, separate markdown and html

Revision ID: 59a69405bf55
Revises: 528adf17f103
Create Date: 2025-08-28 10:24:46.855627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a69405bf55'
down_revision = '528adf17f103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('context_txt', sa.String(), nullable=True),
    sa.Column('research_txt', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['generated_blog_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post_iterations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_markdown', sa.String(), nullable=False))
        batch_op.drop_column('post_context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_iterations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_context', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('content_markdown')

    op.drop_table('blog_post_contexts')
    # ### end Alembic commands ###
