"""add: ideas_txt field to BlogPostContext model

Revision ID: c7ab651e124d
Revises: 8fe16abbbb94
Create Date: 2025-08-28 11:22:33.562703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ab651e124d'
down_revision = '8fe16abbbb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_contexts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ideas_txt', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_contexts', schema=None) as batch_op:
        batch_op.drop_column('ideas_txt')

    # ### end Alembic commands ###
